/*
Gabriel nogueira da Silva 84738
Fillipi Gonçalves da Silva 84649
Gabriel Vinicius Batista 85526
Higor Fernando Holanda 86371
João Vítor de Moraes Ribeiro 86100
Leonardo Marcondes de Godoy Santos 85610
*/

DROP TABLE T_JOGO CASCADE CONSTRAINTS;
DROP TABLE T_JOGADOR CASCADE CONSTRAINTS;
DROP TABLE T_LINHA_TEMPO CASCADE CONSTRAINTS;
DROP TABLE T_CURIOSIDADE CASCADE CONSTRAINTS;
DROP TABLE T_PERSONAGEM CASCADE CONSTRAINTS;

CREATE TABLE T_JOGO (
    ID_JOGO NUMBER(4) PRIMARY KEY NOT NULL,
    PERGUNTA VARCHAR2(1000) NOT NULL,
    RESPOSTA CHAR(1) NOT NULL
);

CREATE TABLE T_JOGADOR (
    ID_JOGADOR NUMBER(4) PRIMARY KEY NOT NULL,
    NOME VARCHAR2(120) NOT NULL,
    PONTUACAO NUMBER(4) NOT NULL
);

CREATE TABLE T_LINHA_TEMPO (
    ID_LINHA_TEMPO NUMBER(4) PRIMARY KEY NOT NULL,
    ANO NUMBER(4) NOT NULL,
    CRONOLOGIA VARCHAR2(1000) NOT NULL
);

CREATE TABLE T_PERSONAGEM (
    ID_PERSONAGEM NUMBER(4) PRIMARY KEY NOT NULL,
    NOME VARCHAR2(120) NOT NULL,
    HISTORIA VARCHAR2(4000) NOT NULL,
    IMAGEM_PERSONAGEM VARCHAR2(1000) NOT NULL
);

CREATE TABLE T_CURIOSIDADE (
    ID_CURIOSIDADE NUMBER(4) PRIMARY KEY NOT NULL,
    DESCRICAO VARCHAR2(4000) NOT NULL,
    IMAGEM_CURIOSIDADE VARCHAR2(1000) NOT NULL
);
commit
